### ISSUE TITLE
Lots of 500 errors in browser console

### ISSUE THREAD

**Issue by JaKXz** [MiniProfiler/rack-mini-profiler#102]
I'm not really sure why I'm getting a lot of these errors... the page I'm working on has some websocket connections/subscriptions going on but those requests are going through just fine and the only errors I'm seeing are from mini profiler. The profiler is working just fine, but it is polluting my console with the errors in the following screenshot.

https://www.dropbox.com/s/rxhedjgb6p51dsv/Screenshot%202014-10-17%2017.09.48.png?dl=0

**Comment by brodock** [comment]
I think I found a similar issue with yours:

The problem happens when using it with unicorn. Unicorn returns 500 because of Rack::Lint::LintError validation.

After I disabled Rack::Lint::LintError, I got all the responses with 404 and content similar to: 
Request not found: kcwkz2gg8fpewr10p5sb - user 127.0.0.1

(/mini-profiler-resources/results)

The major problem here is that for some reason mini-profiler is not handling that request or isn't replying correctly in a json format.

**Comment by MrHubble** [comment]
I'm also using Unicorn and find my console is filled with `POST http://localhost:3000/mini-profiler-resources/results 404 (Not Found)`

**Comment by heyogrady** [comment]
Try removing `/tmp/miniprofiler` and restarting the server. I had the same issue and that did the trick.

**Comment by MrHubble** [comment]
Thanks @heyogrady , that solution (`rm -rf tmp/miniprofiler`) works for me and was also suggested here: https://github.com/MiniProfiler/rack-mini-profiler/issues/71#issuecomment-100867476

**Comment by ramaboo** [comment]
rm -rf did not work for me. Still getting 404's every page load!

**Comment by kbrock** [comment]
@ramaboo are you using a store other than filestore?

**Comment by SamSaffron** [comment]
closing this as stale, I am going to need a repro here to open it.
