### ISSUE TITLE
 Uncaught ReferenceError: DurationMilliseconds is not defined

### ISSUE THREAD

**Issue by denislavski** [MiniProfiler/rack-mini-profiler#121]
When updating from revision 3d41e073cb4ccd276bdb201d877e350012d1dd33
to 7b0696ac73b874b3c7a5a0bfbc8fa2195840c047

**Comment by SamSaffron** [comment]
I need more info here, full backtrace

**Comment by mhlopko** [comment]
I just encountered this issue when I upgraded rack-mini-profiler. The problem was that there was an old tmpl template cached in local storage. The solution is to clear local storage, so the new template gets fetched. I believe this issue can be closed.

**Comment by SamSaffron** [comment]
Interesting, I guess this is a legit bug then, we should have some sort of sha key on the localstorage data that ensures it invalidates correctly.

**Comment by jonathanhefner** [comment]
I believe this has been fixed by https://github.com/MiniProfiler/rack-mini-profiler/commit/6621e74681f012007ab22e7217080ee07b2930bc#diff-810de93622d93c35de753db1b046abc8R508 which switched to using `MiniProfiler::ASSET_VERSION` as the key suffix that [`getVersionedKey`](https://github.com/MiniProfiler/rack-mini-profiler/blob/09a431d07f9d488ed4ec4c000f5b012c9fccb48e/lib/html/includes.js#L29) [uses](https://github.com/MiniProfiler/rack-mini-profiler/blob/09a431d07f9d488ed4ec4c000f5b012c9fccb48e/lib/html/includes.js#L939).

**Comment by SamSaffron** [comment]
Yes this is very much fixed! Thanks.
