### ISSUE TITLE
Profiler shows old data from previous requests

### ISSUE THREAD

**Issue by pavel-clarityhk** [MiniProfiler/rack-mini-profiler#127]
The profiler keeps showing some "stuck" data from old requests on every request - i.e. I have a few rows persisting with the same value and an older timestamp, regardless if this request has been made at all. The actual current request data is still appearing, but with the old one mixed in in between. I have tried restarting the Rails server, restarting my browser and clearing its cache. I haven't seen any other references to this issue and it's not described as a feature. What can I do? Has anyone else had the same problem? Am I missing something?

**Comment by virgild** [comment]
I've seen it once, and a temporary fix is to delete the `tmp/miniprofiler` directory and restarting the Rails server.

**Comment by pavel-clarityhk** [comment]
Thanks, that's quite helpful.

**Comment by bquorning** [comment]
I have experienced the same problem, too. Deleting `tmp/miniprofiler` works fine when using FileStore locally. When using RedisStore on a staging server it’s becoming a pain.

**Comment by SamSaffron** [comment]
I have seen this to in some conditions, we got to add a safeguard here.

On Wed, May 13, 2015 at 6:07 AM, Benjamin Quorning <notifications@github.com

**Comment by keithpitt** [comment]
Yeah, I've noticed this as well. If I keep refreshing the page, it just accumulates requests:
![image](https://cloud.githubusercontent.com/assets/25882/7659923/0d63789e-fb46-11e4-8d03-a92c9291ed39.png)

**Comment by danielnc** [comment]
:+1:

**Comment by bruno-campos** [comment]
:+1: happening with me too

**Comment by SamSaffron** [comment]
Seen stuck data, need a repro to fix this, can someone come up with a
broken spec?

**Comment by chmurph2** [comment]
I've noticed this seems to happen when using the Bullet gem and enabling its `add_footer` option (which displays n+1 query info in the UI.

**Comment by zapo** [comment]
I have the same issue and in my case it looks like it's due to the capping to 10 returned `X-MiniProfiler-Ids` (used client side to fetch individual request results) introduced by this https://github.com/MiniProfiler/rack-mini-profiler/commit/5706186ff354d8f368949bc8c34ad1d18f607ce4

Since only the requested `/results` (max 10) seems to be marked viewed https://github.com/MiniProfiler/rack-mini-profiler/blob/16955540a6fb6e7ad6cf8d08052998fe264652f1/lib/mini_profiler/profiler.rb#L92 next document request will get 1 additional result if my page made 11 requests.

This could be a design choice but I believe if my page make > 10 requests I'd expect  see all of the results at once and that they all get marked viewed. Probably that the flow could be changed so that fetching page request ids would be done in its own JSON GET request instead of being returned in the document response headers so this capping can be removed.

I wonder if as a workaround you can abuse `Rack::MiniProfiler.config.user_provider` to isolate every requests within a page (by passing a page id request header for all the requests of a given document), non returned/viewed results will simply expire but won't get mixed in an other page.

**Comment by bf4** [comment]
Confirming that disabling bullet was sufficient for me. (And rm -rf tmp/miniprofiler also works for a request or two)

**Comment by kbrock** [comment]
For requests 11-20, will they ever get marked 'viewed'?

**Comment by zapo** [comment]
@kbrock no that's the issue for me and that's why they would appear in other page loads

**Comment by SamSaffron** [comment]
I say we fix this once and for all, lets get rid of the concept of backlog
here, just mark absolutely everything read when you load a page.

@kbrock do you want to take this?

**Comment by chmurph2** [comment]
That sounds promising.  Any feedback to give on this at this time?
