### ISSUE TITLE
Old entries not cleaned up when using per-session user provider

### ISSUE THREAD

**Issue by donv** [MiniProfiler/rack-mini-profiler#214]
Hi!

We are using puma (3.1.0-java), rack (1.6.4), rack-mini-profiler (0.9.8), and rails (4.2.5.2).

When we use the default user provider setup, it works fine, but all calls using the same VPN gateway get the same IP, so results are confused.

When we try this user provider:

``` ruby
Rails.application.configure do
  Rack::MiniProfiler.config.user_provider = Proc.new do |env|
    req = Rack::Request.new(env)
    req.session[:session_id] || req.ip
  end
end
```

results are never removed.  The first request displays one result as expected, but the second displays the first and the second result.  The third request displays all three results, and so on.

The example in the doc is very simple, so maybe we have misunderstood something.

Anyway, all help is appreciated :smile: .

**Comment by SamSaffron** [comment]
Can you try on latest? 

Also I wonder if session_id is cycling or ip is incorrect and using load balancer ip. Try logging what 

`req.session[:session_id] || req.ip` returns and seeing if they are stable or not.

**Comment by kbrock** [comment]
Wonder if multi threading is conflicting with in memory store.

Have you tried `Redis`, or file store?

**Comment by pvande** [comment]
I see the same problem with the FileStore.

Part of the problem is that the `user_provider` proc is called in two very different circumstances.  In the normal workflow, it's called at the end of the request, after all the intermediate middleware have run.  However, it's _also_ run when responding to mini-profiler requests, which short-circuit the entire middleware stack, leaving many `env` values null.  As a consequence, we get scenarios like this:

``` ruby
Rack::MiniProfiler.config.user_provider = proc do |env|
  req = Rack::Request.new(env)
  warn [ env['PATH_INFO'], req.session ].inspect
  req.ip
end

# ["/profile", #<ActionDispatch::Request::Session:0x007f91c63ea9e0 ...>]
# ["/profile", #<ActionDispatch::Request::Session:0x007f91c63ea9e0 ...>]
# ["/key.png",  #<ActionDispatch::Request::Session:0x007f91c69981a8 ...>]
# ["/mini-profiler-resources/results", {}]
# ["/mini-profiler-resources/results", {}]
```

**Comment by pvande** [comment]
For what it's worth, we're currently using the Rails-provided CookieStore for our sessions, and our middleware stack looks like this:

```
use Rack::MiniProfiler
use Rack::Sendfile
use ActionDispatch::Static
use Rack::Lock
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007f87b1bfd2a0>
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use MetaRequest::Middlewares::Headers
use BetterErrors::Middleware
use Bugsnag::Rack
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
use MetaRequest::Middlewares::MetaRequestHandler
use MetaRequest::Middlewares::AppRequestHandler
use OmniAuth::Builder
run App::Application.routes
```

**Comment by kbrock** [comment]
I believe this is a javascript issue.

I put in `puts` and brake points throughout this code.
The back end seems to be doing the right thing, it is the front end that is not properly clearing it out.

It sends the "found a new page" to the front end, but it doesn't seem to know when it should clear out the older entries.

**Comment by pvande** [comment]
I'm less certain.  As @SamSaffron alluded, `req.session[:session_id]` isn't stable here, because `req.session` isn't stable.

When `user_provider` is called to generate the request data, it's called with an `env` that's been run through the entire middleware stack.  When R::MP is invoked to fetch the request data, it _also_ calls `user_provider`, but with only a minimal middleware stack (i.e. _maybe_ `Deflate`).

It seems more likely that R::MP is therefore marking the data as read _by a different user_, which is why the Javascript keeps requesting stale data.

**Comment by vlymar** [comment]
Seeing the same behavior in our app, reproducible in dev. For each page load, some invocations of the `user_provider` proc will pass an env where `Rack::Request.new(env).session[:session_id]` is nil. We noticed this because we use warden for authentication, and we wanted to extract a user id with `env['warden'].try(:user).try(:uid)`, but for some invocations this would return null. Falling back on IP in these cases doesn't help, we get the same issue described above where old request data isn't cleared out. Furthermore, after 10 or so stale requests stack up, the profiler widget disappears altogether.

Has anyone found a workaround for user separation in staging/production environments, or does everyone just live with confused results?

Also, i wonder if https://github.com/MiniProfiler/rack-mini-profiler/issues/230 is the same issue?

**Comment by pashamur** [comment]
I ran into the same thing, although interestingly it didn't happen when I ran one instance of Webrick (development), but happened when I ran 8 unicorns off of the same code. I ended up using a hacky workaround which was basically this code in a prefilter, which seems to work for most cases (though not a great solution by any means)

~~~
unless request.xhr?
    user_string = USER_PROVIDER_VALUE
    Rack::MiniProfiler.config.storage_instance.set_all_unviewed(user_string,[])
end
~~~

**Comment by entretechno-jeremiah** [comment]
Thanks everyone in this thread and others for your help! I was able to get this working like so (Ruby 3.1.1/Rails 7.0.2.3):

```ruby
Rack::MiniProfiler.config.user_provider =
  proc do |env|
    req = ActionDispatch::Request.new(env)
    session_store = Rails.application.config.session_store.new(nil, Rails.application.config.session_options)
    rack_session_id, _session = session_store.load_session(req)

    rack_session_id.public_id || req.remote_ip
  end
```

**Comment by nateberkopec** [comment]
I don't think this is a problem with the gem, but rather with people's setups/user_provider callbacks.
