### ISSUE TITLE
Any way to configure start_hidden based on URL param?

### ISSUE THREAD

**Issue by justin808** [MiniProfiler/rack-mini-profiler#284]
Is there any way to configure start_hidden based on URL param?

This can run at startup:

    Rack::MiniProfiler.config.start_hidden = true

But what if I wanted to do something like this. OK?

```ruby
  before_action do
    isAdmin = current_user && current_user.is_admin?
    param_to_enable_miniprofiler = params[:mini_profiler] == "1"
    if isAdmin || param_to_enable_miniprofiler
      # set start_hidden only for this request
      Rack::MiniProfiler.config.start_hidden = param_to_enable_miniprofiler

      Rack::MiniProfiler.authorize_request
    end
  end
```

**Comment by justin808** [comment]
@SamSaffron Should I put in a PR to the README.md?

Also, I'm seeing that I have to CMD-SHIFT-R in chrome to get the miniprofiler to show, quite frequently. Any info on that one? Any way that I can help you debug that one?

**Comment by SamSaffron** [comment]
of course, any PR to improve doco is welcome.

**Comment by cymen** [comment]
If you end up here via Google/searching use the `Alt-P` key combination to toggle it on/off not `?pp=enable` and `?pp=disable`. If I set:

```
Rack::MiniProfiler.config.start_hidden = true
```

Then the `?pp=enable` to toggle it on does not work (but `Alt-P` key combination does).

If I set:

```
Rack::MiniProfiler.config.start_hidden = false
```

Then the URL params do work to enable/disable.

I don't know if this is a bug or intentional so just commenting here for now.
