### ISSUE TITLE
mini profiler version 1.1.0 gives various errors in browser console and doesn't seem to work properly

### ISSUE THREAD

**Issue by kikonen** [MiniProfiler/rack-mini-profiler#406]
It seems that mini profiler is no (with version 1.1.0) dumping various internal errors into console, and profiling of XHR requests doesn't seem work any longer.

Errors dumped in startup
```

Refused to get unsafe header "X-MiniProfiler-Ids"

VM654:3 Uncaught ReferenceError: duration_milliseconds is not defined
    at Object.eval [as profilerTemplate] (eval at r.template (dot.1.1.2.min.js?v=0ade3000608cde95db93022b6576d63a:2), <anonymous>:3:2622)
    at renderTemplate (includes.js?v=0ade3000608cde95db93022b6576d63a:187)
    at buttonShow (includes.js?v=0ade3000608cde95db93022b6576d63a:194)
    at XMLHttpRequest.request.onload (includes.js?v=0ade3000608cde95db93022b6576d63a:158)

VM654:3 Uncaught ReferenceError: duration_milliseconds is not defined
    at Object.eval [as profilerTemplate] (eval at r.template (dot.1.1.2.min.js?v=0ade3000608cde95db93022b6576d63a:2), <anonymous>:3:2622)
    at renderTemplate (includes.js?v=0ade3000608cde95db93022b6576d63a:187)
    at buttonShow (includes.js?v=0ade3000608cde95db93022b6576d63a:194)
    at XMLHttpRequest.request.onload (includes.js?v=0ade3000608cde95db93022b6576d63a:158)

VM654:3 Uncaught ReferenceError: duration_milliseconds is not defined
    at Object.eval [as profilerTemplate] (eval at r.template (dot.1.1.2.min.js?v=0ade3000608cde95db93022b6576d63a:2), <anonymous>:3:2622)
    at renderTemplate (includes.js?v=0ade3000608cde95db93022b6576d63a:187)
    at buttonShow (includes.js?v=0ade3000608cde95db93022b6576d63a:194)
    at XMLHttpRequest.request.onload (includes.js?v=0ade3000608cde95db93022b6576d63a:158)

Refused to get unsafe header "X-MiniProfiler-Ids"
```

**Comment by boo68120** [comment]
Did u got the solution for  
Refused to get unsafe header "X-MiniProfiler-Ids"

**Comment by kikonen** [comment]
My solution so far was to revert back to older version of rack-mini-profiler.

**Comment by SamSaffron** [comment]
@OsamaSayegh can you investigate this ?

**Comment by OsamaSayegh** [comment]
Ok, the `duration_milliseconds is not defined` error is my fault when I switched mini profiler to dot.js from jQuery templating, here is a fix: https://github.com/MiniProfiler/rack-mini-profiler/pull/410

As to `Refused to get unsafe header "X-MiniProfiler-Ids"`, this happens here:

https://github.com/MiniProfiler/rack-mini-profiler/blob/1a242ec5df7c14748d9956347c95f26fc919a524/lib/html/includes.js#L707-L721

Particularly at line 713. This error happens when the browser tries to access a header that's not exposed via `Access-Control-Expose-Headers` or isn't a [simple header](https://www.w3.org/TR/cors/#simple-response-header). Mini Profiler patches the `XMLHttpRequest.prototype.send` method and listens to **all** requests and tries to get the `X-MiniProfiler-Ids` from every response. So if a request is made to a different origin, you'll see this error in the console (unless the header is present and exposed which is unlikely).

The error is harmless, meaning it's just a message printed to the console and it doesn't halt execution so everything else will run as usual. However, should Mini Profiler not attach a `load` event to requests that are made to different origins @SamSaffron?

**Comment by SamSaffron** [comment]
Yeah we should probably bypass origins that we do not know about. Maybe when we load we quickly check where the response came from and ignore it if its not in our whitelisted origins? 

I agree it is not nice to be erroring here. 

Alternatively can we check if something is exposed and not even reach for it if we know we have no access?

**Comment by kikonen** [comment]
v1.1.3 didn't fail immediately, but own custom counter times are not shown in results. Only total percentage for for those are shown.

**Comment by kikonen** [comment]
![Screenshot 2019-10-31 16 48 24](https://user-images.githubusercontent.com/478935/67957721-b47f0900-fbfe-11e9-90cd-c6e45edfded5.png)
vs.

![Screenshot 2019-10-31 16 51 58](https://user-images.githubusercontent.com/478935/67957768-c6f94280-fbfe-11e9-9722-8c1fae5df670.png)

**Comment by kikonen** [comment]
ping?

**Comment by OsamaSayegh** [comment]
Apologies for the delay here @kikonen. I'm caught up with something else and haven't had a chance to look at this yet. I should be able to investigate and fix this in a couple of weeks. Thank you for your patience.

**Comment by kikonen** [comment]
Tried to debug a bit,

It looks like it's failing due to incorrect scoping of custom_timing_names in
```
<script id="timingTemplate" type="text/x-dot-tmpl">
   ...
  {{~ it.page.custom_timing_names :value}}
    ...
```
Fails since there is no "it.page.custom_timing_names". 

Instead there seems to be (depending of table row)
- "it.page.page.custom_timing_names"
- "it.page.page.page.page.custom_timing_names"
- "it.page.page.page.page.page.custom_timing_names"

**Comment by OsamaSayegh** [comment]
@kikonen I did submit https://github.com/MiniProfiler/rack-mini-profiler/pull/428 to fix this and it was merged a couple of weeks ago. However it doesn't look like we have released a new version. I don't have push permissions to rubygems, so we'll need to wait for @SamSaffron to do it (sometime next week probably).

**Comment by kikonen** [comment]
Just tested with master, and it seems to work. Thus I will for a moment just use "master" from gitbug

**Comment by SamSaffron** [comment]
doing a new release today!
