### ISSUE TITLE
mini-profiler removes cache-control header

### ISSUE THREAD

**Issue by thedarkside** [MiniProfiler/rack-mini-profiler#63]
The cache-control headers without mini-profiler:

```
HTTP/1.1 200 OK
Date: Fri, 07 Mar 2014 12:48:37 GMT
Content-Type: image/jpeg
Status: 200 OK
Content-Length: 340038
Content-Disposition: filename="14tdysnuvo.jpg"
Cache-Control: public, max-age=31536000
ETag: "39f18a9d2ab41214aa62c3fe28efcd7d44e92ea9"
X-Request-Id: dce5d9cd-cfbb-4362-a42f-a7b62ded6574
X-Runtime: 0.100084
```
and with mini-profiler enabled:

```
HTTP/1.1 200 OK
Date: Fri, 07 Mar 2014 12:33:58 GMT
Status: 200 OK
Content-Type: image/jpeg
Content-Length: 340038
Content-Disposition: filename="14tdysnuvo.jpg"
Cache-Control: must-revalidate, private, max-age=0
X-Request-Id: 97c0797a-71cb-429a-800e-963bcf93f50d
X-Runtime: 0.104847
Set-Cookie: __profilin=p%3Dt; path=/
Set-Cookie: __profilin=p%3Dt; path=/
Set-Cookie: __profilin=p%3Dt; path=/
X-MiniProfiler-Ids: ["mryxzb2q56i903vzo703","g7x7vc8680669mha5h0q","bpe4damr7lhmz98m76s9","rxi35n4b1ucuszoil3g5","96f75o5579wx53nhjwqv","5obvbow2o2cdbplrfhud","rnr6i46hnelap0abdtx9","wsrkubaekehj9gk1ndxo","dc2l6imvfwvzl7ta66pw","2wuoraq2z97ox8rfkdsa"]
```
can ayone explain the reason why mini-profiler removes the e-tag and cache-control headers and how to disable this behavior?
I have an test-environment and want both, the miniprofiler and a working cache in front of the app.

**Comment by teoulas** [comment]
If you deploy on Heroku and follow their [recommendation to serve assets from your Rails app](https://devcenter.heroku.com/articles/rails-4-asset-pipeline#serve-assets) with a CDN in front of it, then your CDN will never cache any assets, since mini-profiler overwrites the Cache-Control header. This is easily fixed by configuring the `skip_paths` option to skip any asset paths. However, it took me ages to debug and find out. Maybe it would be a good idea to skip `/assets/` by default?

**Comment by SamSaffron** [comment]
sure I am happy to add something like this to the railstie if you want to
give it a shot.
